AngelAld/proyecto_calidad

README.md
=> prueba proteccion

capaNegocio/controlador_planestudio.py, capaPresentacion/planEstudio/plan_estudio.py, capaPresentacion/planEstudio/templates/frm_agregar_plan_estudio.html, capaPresentacion/planEstudio/templates/frm_editar_plan_estudio.html, capaPresentacion/planEstudio/templates/mantenimiento_plan_estudio.html, capaPresentacion/planEstudio/templates/planEstudio.html, extras/plan_estudio.sql, main.py, templates/maestra/sidebar.html
=> plan de estudio

capaNegocio/controlador_lineadesarrollo.py, capaPresentacion/lineaDesarrollo/linea_desarrollo.py, capaPresentacion/lineaDesarrollo/templates/frm_agregar_lineaDesarrollo.html, capaPresentacion/lineaDesarrollo/templates/frm_editar_lineaDesarrollo.html, capaPresentacion/lineaDesarrollo/templates/lineaDesarrollo.html, capaPresentacion/lineaDesarrollo/templates/mantenimiento_linea_desarrollo.html
=> líneaDesarrollo-estado

capaNegocio/controlador_lineadesarrollo.py, capaPresentacion/lineaDesarrollo/linea_desarrollo.py, capaPresentacion/lineaDesarrollo/templates/frm_editar_lineaDesarrollo.html, capaPresentacion/lineaDesarrollo/templates/mantenimiento_linea_desarrollo.html
=> LineaDesarrollo-estado-agregar-eliminar

capaNegocio/controlador_lineadesarrollo.py, capaPresentacion/lineaDesarrollo/linea_desarrollo.py, capaPresentacion/lineaDesarrollo/templates/lineaDesarrollo.html, capaPresentacion/lineaDesarrollo/templates/mantenimiento_linea_desarrollo.html
=> LineaDesarrollo-agregar-editar-eliminar-agregar

capaNegocio/controlador_informe_inicial_es.py, capaPresentacion/informe_inicial_es/informe_inicial_es.py, capaPresentacion/informe_inicial_es/templates/informe_inicial_es.html, main.py, templates/maestra/sidebar.html
Listado de informe inicial estudiante
=> agregue informe inicial estudiante

capaNegocio/controlador_informe_inicial_em.py, capaPresentacion/informe_inicial_em/informe_inicial_em.py, capaPresentacion/informe_inicial_em/templates/informe_inicial_em.html, capaPresentacion/informe_inicial_es/templates/frm_agregar_informe_inicial_es.html, main.py, templates/maestra/sidebar.html
lista de informe inicial empresa
=> agregue informe inicial empresa

capaNegocio/controlador_ficha_desempeno.py, capaPresentacion/ficha_desempeno/ficha_desempeno.py, capaPresentacion/ficha_desempeno/templates/ficha_desempeno.html, main.py, templates/maestra/sidebar.html
lista de ficha de evaluacion de desempeño
=> agregue ficha desempeño

capaNegocio/controlador_informe_final_em.py, capaPresentacion/informe_final_em/informe_final_em.py, capaPresentacion/informe_final_em/templates/informe_final_em.html, main.py, templates/maestra/sidebar.html
lista de informe final empresa
=> agregue informe final empresa

capaNegocio/controlador_informe_final_es.py, capaPresentacion/informe_final_es/informe_final_es.py, capaPresentacion/informe_final_es/templates/informe_final_es.html, main.py, templates/maestra/sidebar.html
lista de informe final estudiante
=> agregue informe final estudiante

capaNegocio/controlador_jefe_inmediato.py, capaPresentacion/Jefe_Inmediato/jefe_inmediato.py, capaPresentacion/Jefe_Inmediato/templates/frm_agregar_jefe_inmediato.html, capaPresentacion/Jefe_Inmediato/templates/jefe_inmediato.html, capaPresentacion/Jefe_Inmediato/templates/mantenimiento_jefe_inmediato.html, main.py, templates/maestra/sidebar.html
Por ahora lista todos los jefes inmediatos
=> jefe inmediato

capaPresentacion/ficha_desempeno/templates/mantenimiento_ficha_desempeno.html, capaPresentacion/informe_final_em/informe_final_em.py, capaPresentacion/informe_final_em/templates/informe_final_em.html, capaPresentacion/informe_final_em/templates/mantenimiento_informe_final_em.html, capaPresentacion/informe_final_es/informe_final_es.py, capaPresentacion/informe_final_es/templates/informe_final_es.html, capaPresentacion/informe_final_es/templates/mantenimiento_informe_final_es.html, capaPresentacion/informe_inicial_em/informe_inicial_em.py, capaPresentacion/informe_inicial_em/templates/informe_inicial_em.html, capaPresentacion/informe_inicial_em/templates/mantenimiento_informe_inicial_em.html, capaPresentacion/informe_inicial_es/templates/mantenimiento_informe_inicial_es.html
=> documentos

capaNegocio/controlador_informe_inicial_es.py, capaPresentacion/ficha_desempeno/templates/mantenimiento_ficha_desempeno.html, capaPresentacion/informe_final_em/templates/mantenimiento_informe_final_em.html, capaPresentacion/informe_final_es/templates/mantenimiento_informe_final_es.html, capaPresentacion/informe_inicial_em/templates/mantenimiento_informe_inicial_em.html, capaPresentacion/informe_inicial_es/informe_inicial_es.py, capaPresentacion/informe_inicial_es/templates/mantenimiento_informe_inicial_es.html, extras/informe_inicial_es.sql
los 4 informes y ficha evaluacion
=> Rama culquii

capaPresentacion/docenteApoyo/templates/mantenimiento_docente.html
Avísame si quieres que nombre solo acepte letras
=> validando docente

capaNegocio/controlador_informe_inicial_em.py, capaPresentacion/informe_inicial_em/informe_inicial_em.py, capaPresentacion/informe_inicial_em/templates/frm_editar_informe_inicial_em.html, capaPresentacion/informe_inicial_em/templates/informe_inicial_em.html, capaPresentacion/informe_inicial_em/templates/mantenimiento_informe_inicial_em.html, extras/informe_inicial_em.sql
lista informe inicial empresa, ademas en mantenimiento muestran los datos de estudiante y centro de practica.
=> informe inicial empresa

capaNegocio/controlador_informe_inicial_em.py, capaPresentacion/informe_inicial_em/informe_inicial_em.py, capaPresentacion/informe_inicial_em/templates/frm_editar_informe_inicial_em.html, capaPresentacion/informe_inicial_em/templates/mantenimiento_informe_inicial_em.html, extras/informe_inicial_em.sql
=> informe inicial emmpresa

capaNegocio/controlador_informe_final_em.py, capaPresentacion/informe_final_em/informe_final_em.py, capaPresentacion/informe_final_em/templates/frm_editar_informe_final_em.html, capaPresentacion/informe_final_em/templates/informe_final_em.html, extras/informe_final_em.sql
informe final empresa barturen - sanchez
=> informe final empresa barturen - sanchez

capaNegocio/controlador_informe_inicial_em.py, capaPresentacion/informe_inicial_em/informe_inicial_em.py, capaPresentacion/informe_inicial_em/templates/frm_editar_informe_inicial_em.html, capaPresentacion/informe_inicial_em/templates/mantenimiento_informe_inicial_em.html
=> informe inicial eempresa

capaNegocio/controlador_facultad.py, capaNegocio/controlador_informe_final_em.py, capaPresentacion/facultad/facultades.py, capaPresentacion/facultad/templates/facultades.html, capaPresentacion/facultad/templates/reporte_facultad.html, capaPresentacion/informe_final_em/informe_final_em.py, capaPresentacion/informe_final_em/templates/frm_editar_informe_final_em.html, capaPresentacion/informe_final_em/templates/informe_final_em.html, capaPresentacion/informe_final_em/templates/mantenimiento_informe_final_em.html, capaPresentacion/informe_inicial_em/informe_inicial_em.py, main.py
Avance02 Informe final empresa Barturen-Sanchez
=> informe final avance02 barturen-sanchez

capaNegocio/controlador_informe_final_em.py, capaPresentacion/informe_final_em/informe_final_em.py, capaPresentacion/informe_final_em/templates/mantenimiento_informe_final_em.html
avance 03 informe final empresa
=> avance03 barturen-sanchez
